fix wait

diff --git a/push-runner/opt/k8sci-wait-job b/push-runner/opt/k8sci-wait-job
--- a/push-runner/opt/k8sci-wait-job
+++ b/push-runner/opt/k8sci-wait-job
@@ -1,11 +1,7 @@
 #!/bin/sh
-set -e
 
 K8SCI_WAIT_JOB_TYPE=${1:-"$K8SCI_WAIT_JOB_TYPE"}
 K8SCI_CONTEXT=${2:-"$K8SCI_CONTEXT"}
-K8SCI_WAIT_TIMEOUT=${3:-"$K8SCI_WAIT_TIMEOUT"}
-
-K8SCI_WAIT_TIMEOUT=${K8SCI_WAIT_TIMEOUT:-"60m"}
 
 if [ -z "$K8SCI_WAIT_JOB_TYPE" ]; then
   echo "missing 1 required argument or K8SCI_WAIT_JOB_TYPE env var"
@@ -16,32 +12,23 @@ if [ -z "$K8SCI_GID" ]; then
   exit 1
 fi
 
-kubectl \
-  --server=$K8SCI_K8S_SERVER --token=$K8SCI_K8S_TOKEN \
-  --namespace=$K8SCI_K8S_NS \
-  wait \
-    --for=condition=complete \
-    "job/runner-${K8SCI_GID}-${K8SCI_WAIT_JOB_TYPE}-${K8SCI_CONTEXT}" \
-    --timeout=$K8SCI_WAIT_TIMEOUT &
-completion_pid=$!
+JOB="job/runner-${K8SCI_GID}-${K8SCI_WAIT_JOB_TYPE}-${K8SCI_CONTEXT}"
 
-kubectl \
-  --server=$K8SCI_K8S_SERVER --token=$K8SCI_K8S_TOKEN \
-  --namespace=$K8SCI_K8S_NS \
-  wait \
-    --for=condition=failed \
-    "job/runner-${K8SCI_GID}-${K8SCI_WAIT_JOB_TYPE}-${K8SCI_CONTEXT}" \
-    --timeout=$K8SCI_WAIT_TIMEOUT  && exit 1 &
-failure_pid=$!
+retval_complete=1
+retval_failed=1
+while [[ $retval_complete -ne 0 ]] && [[ $retval_failed -ne 0 ]]; do
+  sleep 2
+  output=$(kubectl --server=$K8SCI_K8S_SERVER --token=$K8SCI_K8S_TOKEN --namespace=$K8SCI_K8S_NS \
+    wait --for=condition=complete $JOB --timeout=0 2>&1)
+  retval_complete=$?
+  output=$(kubectl --server=$K8SCI_K8S_SERVER --token=$K8SCI_K8S_TOKEN --namespace=$K8SCI_K8S_NS \
+    wait --for=condition=failed $JOB --timeout=0 2>&1)
+  retval_failed=$?
+done
 
-wait -n $completion_pid $failure_pid
-
-exit_code=$?
-
-if (( $exit_code == 0 )); then
-  echo '{"status":"succeed"}'
+if [ $retval_failed -eq 0 ]; then
+  echo "$JOB failed"
+  exit 1
 else
-  echo '{"status":"failed"}'
+  echo "$JOB complete"
 fi
-
-exit $exit_code
